/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.parcial.pkg1;

/**
 *
 * @author hector
 */
public class Forma extends javax.swing.JFrame {
    //Datos donde se encuentran todas las letras
    private String tabla = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    
    
    public Forma() {
        initComponents();
    }
    
    private String limpiar_texto(String texto){
    // Primero se limpia el texto para que no aparezcan cosas raras
    
    texto = texto.replaceAll("\n","");
    texto=texto.toUpperCase();
    for(int i=0;i<texto.length();i++){
        //Se crea un for que llenara el nuevo char
        int posicion = tabla.indexOf(texto.charAt(i)); //charat regresa el valor del arreglo
            if(posicion == -1){ 
            texto=texto.replace(texto.charAt(i),' ');
            //En caso que no aparezca en la tabla de caracteres
            //Tiene que ser eliminado
            }
    }
        return texto;
    }
    
    public String Encriptar(String texto, int llave){
        
        String limpiar_texto = limpiar_texto(texto);
        //Utilizar el texto limpirado
        String encriptado = "";
        //Tener un string donde meter los nuevos caracteres
    for (int j=0;j<limpiar_texto.length();j++){
        int posicion = tabla.indexOf(limpiar_texto.charAt(j));
    
        if((posicion+llave)<tabla.length())
            {
            encriptado += tabla.charAt(posicion+llave);
            //llenar el encriptado de acuerdo a la posicion que toma
            }
                else{
            encriptado +=tabla.charAt((posicion+llave)-tabla.length());
                //Si se pasa, pues empezar la tabla nuevamente
                }
         }
        return encriptado;
        }

    public String Desencriptar(String texto, int llave){
        
        String limpiar_texto = limpiar_texto(texto);
        
        String desencriptado = "";
        
        for (int  k=0;k<limpiar_texto.length();k++){
        
            int posicion = tabla.indexOf(limpiar_texto.charAt(k));
        //En si lo que hace, es lo contrario al metodo encriptar
                if((posicion - llave)<0){
            desencriptado +=tabla.charAt((posicion-llave)+tabla.length());
                } 
                    else{
            desencriptado +=tabla.charAt(posicion-llave);
                        }
        
        }
        return desencriptado;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_Desencriptado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_Encriptado = new javax.swing.JTextArea();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        boton_Encriptar = new javax.swing.JButton();
        boton_Desencriptar = new javax.swing.JButton();
        lbl_llave = new java.awt.Label();
        txtfield_Llave = new javax.swing.JTextField();
        btn_Borrar = new javax.swing.JButton();

        jButton1.setText("Borrar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cesar");

        textArea_Desencriptado.setColumns(20);
        textArea_Desencriptado.setRows(5);
        jScrollPane1.setViewportView(textArea_Desencriptado);

        textArea_Encriptado.setColumns(20);
        textArea_Encriptado.setRows(5);
        jScrollPane2.setViewportView(textArea_Encriptado);

        label1.setText("Mensaje Original");

        label2.setText("Mensaje Encriptado");

        boton_Encriptar.setText("Encriptar");
        boton_Encriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EncriptarActionPerformed(evt);
            }
        });

        boton_Desencriptar.setText("Desencriptar");
        boton_Desencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_DesencriptarActionPerformed(evt);
            }
        });

        lbl_llave.setText("Llave");

        btn_Borrar.setText("Borrar");
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_Encriptar)
                        .addGap(18, 18, 18)
                        .addComponent(boton_Desencriptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_llave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfield_Llave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Borrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lbl_llave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boton_Encriptar)
                                .addComponent(boton_Desencriptar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfield_Llave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Borrar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_EncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EncriptarActionPerformed
       
        //Se obtiene el text
        String entrada = textArea_Desencriptado.getText();
        //se obtiene la llave
        int llave = Integer.parseInt(txtfield_Llave.getText());
        //se realiza la encriptacion con la llave. 
        //De acuerdo a la int posicion
            if(llave<=26){
            textArea_Encriptado.setText(Encriptar(entrada,llave));
            }
    }//GEN-LAST:event_boton_EncriptarActionPerformed

    private void boton_DesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_DesencriptarActionPerformed
        
        //Se obtiene texto y llave
        String entrada = textArea_Encriptado.getText();
        int llave = Integer.parseInt(txtfield_Llave.getText());
        //Se realiza la desencriptacion con la llave
            if(llave<=26){
            textArea_Encriptado.setText(Desencriptar(entrada,llave));
            }
    }//GEN-LAST:event_boton_DesencriptarActionPerformed

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
       
        //deja todos los valores en "" nada uwu
        textArea_Desencriptado.setText("");
        textArea_Encriptado.setText("");
    }//GEN-LAST:event_btn_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Desencriptar;
    private javax.swing.JButton boton_Encriptar;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label lbl_llave;
    private javax.swing.JTextArea textArea_Desencriptado;
    private javax.swing.JTextArea textArea_Encriptado;
    private javax.swing.JTextField txtfield_Llave;
    // End of variables declaration//GEN-END:variables
}
