/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.parcial.pkg1;

/**
 *
 * @author hector
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Cesar = new javax.swing.JButton();
        btn_Atbash = new javax.swing.JButton();
        btn_Vigenere = new javax.swing.JButton();
        btn_Bifid = new javax.swing.JButton();
        btn_XOR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jLabel1.setText("Elige el metodo de encriptacion deseado");

        btn_Cesar.setText("Cesar");
        btn_Cesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CesarActionPerformed(evt);
            }
        });

        btn_Atbash.setText("AtBash");
        btn_Atbash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtbashActionPerformed(evt);
            }
        });

        btn_Vigenere.setText("Vigenere");
        btn_Vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VigenereActionPerformed(evt);
            }
        });

        btn_Bifid.setText("Bifid");
        btn_Bifid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BifidActionPerformed(evt);
            }
        });

        btn_XOR.setText("XOR");
        btn_XOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Cesar)
                    .addComponent(btn_Atbash)
                    .addComponent(btn_Vigenere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Bifid)
                    .addComponent(btn_XOR))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cesar)
                    .addComponent(btn_Bifid))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Atbash)
                    .addComponent(btn_XOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Vigenere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Las ventanas se han puesto en dispose para no cerrrar todo
    private void btn_CesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CesarActionPerformed
        //Solamente manda a llamar el Jframe Forma (Cesar)
        new Forma().setVisible(true);
    }//GEN-LAST:event_btn_CesarActionPerformed

    private void btn_AtbashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtbashActionPerformed
        // Solamente manda a llamar el Jframe AtBash
        new Atbash().setVisible(true);
    }//GEN-LAST:event_btn_AtbashActionPerformed

    private void btn_VigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VigenereActionPerformed
        // Solamente manda a llamar el Jframe Vigenere_forma
        new Vigenere_forma().setVisible(true);
    }//GEN-LAST:event_btn_VigenereActionPerformed

    private void btn_XORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XORActionPerformed
        // Solamente manda a llamar el Jframe XOR_Form
        new XOR_Form().setVisible(true);
    }//GEN-LAST:event_btn_XORActionPerformed

    private void btn_BifidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BifidActionPerformed
        // Solamente manda a llamar el Jframe Bifid_Forma
        new Bifid_Forma().setVisible(true);
    }//GEN-LAST:event_btn_BifidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atbash;
    private javax.swing.JButton btn_Bifid;
    private javax.swing.JButton btn_Cesar;
    private javax.swing.JButton btn_Vigenere;
    private javax.swing.JButton btn_XOR;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
