/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.parcial.pkg1;

/**
 *
 * @author hector
 */
public class Vigenere_forma extends javax.swing.JFrame {

    /**
     * Creates new form Vigenere_forma
     */
    public Vigenere_forma() {
        initComponents();
    }

    public String Encriptar(String texto, String llave){
        String encriptado = "";
        //Se convierte en mayusculas y se eliminan cosas raras
        llave = llave.toUpperCase();
        texto = texto.toUpperCase();
        texto = texto.replaceAll("\n","");
        //Se llena el encriptado con un for
        for (int i = 0, j = 0; i < texto.length(); i++) {
            char x = texto.charAt(i);
            if (x < 'A' || x > 'Z') {
                continue;
            }
            //Formula de internet hehehe
            //https://www.geeksforgeeks.org/vigenere-cipher/
            encriptado += (char) ((x + llave.charAt(j) - 2 * 'A') % 26 + 'A');
            j = ++j % llave.length();
        }
        return encriptado;
    }
    
    public String Desencriptar(String texto, String llave){
        String desencriptado ="";
        //Se convierte en mayusculas y se eliminan cosas raras
        texto = texto.toUpperCase();
        llave = llave.toUpperCase();
        texto = texto.replaceAll("\n","");
        //Mismo algoritmo de internet
        //https://www.geeksforgeeks.org/vigenere-cipher/
        for (int i = 0, j = 0; i < texto.length(); i++) {
            char c = texto.charAt(i);
            if (c < 'A' || c > 'Z') {
                continue;
            }
            desencriptado += (char) ((c - llave.charAt(j) + 26) % 26 + 'A');
            j = ++j % llave.length();
        }
        return desencriptado;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Original = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Encriptado = new javax.swing.JTextArea();
        btn_Encriptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtField_Llave = new javax.swing.JTextField();
        btn_Desencriptar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vigenere");

        jLabel1.setText("Texto Original");

        txt_Original.setColumns(20);
        txt_Original.setRows(5);
        jScrollPane1.setViewportView(txt_Original);

        jLabel2.setText("Texto Encriptado");

        txt_Encriptado.setColumns(20);
        txt_Encriptado.setRows(5);
        jScrollPane2.setViewportView(txt_Encriptado);

        btn_Encriptar.setText("Encriptar");
        btn_Encriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EncriptarActionPerformed(evt);
            }
        });

        jLabel3.setText("Llave");

        btn_Desencriptar.setText("Desencriptar");
        btn_Desencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DesencriptarActionPerformed(evt);
            }
        });

        btn_Borrar.setText("Borrar");
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Encriptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtField_Llave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Desencriptar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Borrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Encriptar)
                    .addComponent(jLabel3)
                    .addComponent(txtField_Llave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Desencriptar)
                    .addComponent(btn_Borrar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        // TODO add your handling code here:
        txt_Original.setText("");
        txt_Encriptado.setText("");
    }//GEN-LAST:event_btn_BorrarActionPerformed

    private void btn_EncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EncriptarActionPerformed
        // TODO add your handling code here:
        String entrada = txt_Original.getText();
        String llave = txtField_Llave.getText();
        String Salida = Encriptar(entrada,llave);
        txt_Encriptado.setText(Salida);
    }//GEN-LAST:event_btn_EncriptarActionPerformed

    private void btn_DesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DesencriptarActionPerformed
        // TODO add your handling code here:
        String entrada = txt_Encriptado.getText();
        String llave = txtField_Llave.getText();
        String Salida = Desencriptar(entrada,llave);
        txt_Original.setText(Salida);
    }//GEN-LAST:event_btn_DesencriptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vigenere_forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vigenere_forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vigenere_forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vigenere_forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vigenere_forma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Desencriptar;
    private javax.swing.JButton btn_Encriptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtField_Llave;
    private javax.swing.JTextArea txt_Encriptado;
    private javax.swing.JTextArea txt_Original;
    // End of variables declaration//GEN-END:variables
}
